### ISSUE TITLE
成就模块失效

### ISSUE THREAD

**Issue by ElkGetLost** [KINOVE/StarRail-EasyScript#1]
分辨率是1920*1080的，提示没有新的成就奖励需要领取。

**Comment by Reroll24** [comment]
~~见鬼，我还以为没人用这脚本~~

这模块我好久没碰过了，这几天我看看

**Comment by ElkGetLost** [comment]
大佬，我用连点器点完。应该是分辨率引起的点位问题。删不掉这议题你给我删一下。

**Comment by Reroll24** [comment]
暂时不用删，我也确实很久没动过这部分代码，也不知道失效了没，改天测试一下。

（手头的账号现在没有成就可以领。）

另外我检测成就是否领取，是在菜单界面判断图片中的位置有没有红点，然后才会进入成就功能。如果你的账号还处于新手期，功能没有完全开放，那么在菜单界面的这个位置不一定是“成就”按钮，这一点需要注意一下。

![image](https://github.com/KINOVE/StarRail-EasyScript/assets/41948123/51e8a28b-5723-4f98-bc60-522969adbcfe)


~~其实我长草后也是用连点功能（ctrl+alt+长按鼠标左键）领取的成就奖励~~
